- name: Creating prometheus user group
  group: name="{{groupId}}"
  become: true
  tags:
    - prom

- name: Check if Prometheus is already installed
  stat:
    path: "/usr/local/bin/prometheus"
  register: prometheus_installed
  tags:
    - prom

- name: Creating prometheus user
  user:
    name: "{{userId}}"
    group: "{{groupId}}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{userId}} nologin User"
    createhome: "no"
    state: present
  when: not prometheus_installed.stat.exists
  tags:
    - prom


- name: Install prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
  when: not prometheus_installed.stat.exists
  tags:
    - prom


- name: Copy prometheus file to bin
  copy:
    src: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    owner: "{{userId}}"
    group: "{{groupId}}"
    remote_src: yes
    mode: 0755
  when: not prometheus_installed.stat.exists
  tags:
    - prom

- name: Delete prometheus tmp folder
  file:
    path: '/tmp/prometheus-{{ version }}.linux-amd64'
    state: absent
  when: not prometheus_installed.stat.exists
  tags:
    - prom

- name: Creates directory
  file: 
    path: "/data/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755
  when: not prometheus_installed.stat.exists
  tags:
    - prom

- name: Creates directory
  file: 
    path: "/etc/prometheus/"
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: 0755
  tags:
    - prom
  

- name: config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.conf
  tags:
    - prom

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: 
    - systemd_reload
    - event_restart_prometheus
  tags:
    - prom

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
  tags:
    - prom

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
