---
- name: Add Nginx repository key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add Nginx repository
  apt_repository:
    repo: "deb https://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
    state: present

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create Directory
  file:
    path: /usr/share/html/
    state: directory
    owner: "{{userId}}"
    group: "{{groupId}}"
    mode: '0755'


- name: Install dependencies for building Nginx module
  apt:
    name:
      - git
      - build-essential
      - libpcre3
      - libpcre3-dev
      - zlib1g
      - zlib1g-dev
      - libssl-dev
    state: present
- name: Download Nginx source code
  git:
    repo: https://github.com/nginx/nginx.git
    dest: /usr/local/src/nginx
    version: release-{{ nginx_version }}

- name: Download VTS module
  git:
    repo: https://github.com/vozlt/nginx-module-vts.git
    dest: /usr/local/src/nginx-module-vts

- name: Configure Nginx with VTS module
  ansible.builtin.command:
    cmd: ./auto/configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --add-module=/usr/local/src/nginx-module-vts
  args:
    chdir: /usr/local/src/nginx
    creates: /usr/local/src/nginx/objs/nginx

- name: Build Nginx
  ansible.builtin.command:
    cmd: make
  args:
    chdir: /usr/local/src/nginx
    creates: /usr/local/src/nginx/objs/nginx

- name: Install Nginx
  ansible.builtin.command:
    cmd: make install
  args:
    chdir: /usr/local/src/nginx
    creates: /usr/sbin/nginx

- name: Backup existing Nginx binary
  command: sudo mv /usr/sbin/nginx /usr/sbin/nginx.backup
  args:
    creates: /usr/sbin/nginx.backup

- name: Replace Nginx binary
  copy:
    src: /usr/local/src/nginx/objs/nginx
    dest: /usr/sbin/nginx
    mode: '0755'
    remote_src: yes

- name: Create config file html from template
  template:
    src: index.html
    dest: /usr/share/html/index.html
  tags: indexhtml

- name: Create config file from template
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Create Directory
  ansible.builtin.file:
    path: /usr/share/html/
    state: directory
    owner: "{{ userId }}"
    group: "{{ groupId }}"
    mode: '0755'

- name: Install binary vts_exporter
  ansible.builtin.unarchive:
    src: "{{ nginx_vts_exporter_binary_url }}"
    dest: "/usr/local/bin/"
    remote_src: yes

- name: Configure vts_exporter
  ansible.builtin.template:
    src: default-config.j2
    dest: "/etc/default/{{ nginx_vts_exporter_service_name }}"

- name: Create systemd unit for vts_exporter
  ansible.builtin.template:
    src: systemd-unit.j2
    dest: "/etc/systemd/system/{{ nginx_vts_exporter_service_name }}.service"

- name: Enable and start vts_exporter service
  ansible.builtin.systemd:
    name: "{{ nginx_vts_exporter_service_name }}"
    enabled: true
    state: started